import { useEffect, useRef, useState } from 'react'
import Icon from './Icon'
import { animate } from 'animejs'

function UploadCard({ onUpload, compact = false, isUploading = false }) {
  const inputRef = useRef(null)
  const cardRef = useRef(null)
  const statusRef = useRef(null)
  const [file, setFile] = useState(null)
  const [status, setStatus] = useState('idle')
  const [error, setError] = useState('')
  useEffect(() => { if (!cardRef.current) return undefined; const animation = animate(cardRef.current, { opacity: [0, 1], translateY: [18, 0], duration: 700, ease: 'outExpo' }); return () => animation.revert() }, [])
  useEffect(() => { if (!statusRef.current || status === 'idle') return undefined; const reduced = window.matchMedia('(prefers-reduced-motion: reduce)').matches; const animation = animate(statusRef.current, status === 'uploading' && !reduced ? { translateX: [-3, 3], duration: 700, ease: 'inOutSine', alternate: true, loop: true } : { scale: [.92, 1], opacity: [0, 1], duration: 350, ease: 'outExpo' }); return () => animation.revert() }, [status])
  async function handleFile(event) { const [selected] = event.target.files; event.target.value = ''; if (!selected) return; setFile(selected); setError(''); setStatus('uploading'); try { await onUpload(selected); setStatus('success'); window.setTimeout(() => { setFile(null); setStatus('idle') }, 2400) } catch (uploadError) { setError(uploadError.message || 'Upload could not be completed.'); setStatus('error') } }
  const size = file ? `${(file.size / 1024 / 1024).toFixed(file.size < 1024 * 1024 ? 2 : 1)} MB` : ''
  return <section ref={cardRef} className={`relative overflow-hidden rounded-[26px] border border-[#9aaf81] bg-[#f0f3df] text-[#19311e] shadow-[0_12px_30px_rgba(29,54,31,.1)] ${compact ? 'p-5' : 'p-6 sm:p-7'}`}><div className="absolute -right-7 -top-9 size-32 rounded-full border border-[#8cab65]/35" /><div className="absolute right-8 top-4 text-3xl text-[#d97d5e]">✦</div><div className="relative flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[.16em] text-[#537040]">Always ready</p><h2 className="display-font mt-1 text-2xl font-bold tracking-[-.04em]">Add a new document</h2><p className="mt-1 max-w-md text-sm text-[#52664d]">Drop in a college circular, notice, syllabus or opportunity.</p></div><button disabled={isUploading || status === 'uploading'} onClick={() => inputRef.current?.click()} className="inline-flex shrink-0 items-center justify-center gap-2 rounded-xl bg-[#285137] px-4 py-3 text-sm font-bold text-[#fbf8e9] transition hover:scale-[1.02] disabled:cursor-wait disabled:opacity-70"><Icon name="upload" className="size-5" />{status === 'uploading' ? 'Uploading…' : 'Upload PDF'}</button></div>{file && <div ref={statusRef} className={`relative mt-5 flex items-center gap-3 rounded-2xl border px-4 py-3 ${status === 'error' ? 'border-[#d97d5e] bg-[#fff0e9]' : status === 'success' ? 'border-[#86b45b] bg-[#e6f4cb]' : 'border-[#b7c996] bg-[#f8faea]'}`}><span className={`grid size-10 shrink-0 place-items-center rounded-xl ${status === 'success' ? 'bg-[#d7f46d]' : 'bg-[#dce8c4]'}`}>{status === 'success' ? '✓' : <Icon name="file" className="size-5" />}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{file.name}</p><p className="mt-0.5 text-xs text-[#63755b]">{file.name.split('.').pop()?.toUpperCase() || 'FILE'} · {size}</p></div><p className={`text-xs font-bold ${status === 'error' ? 'text-[#a64e38]' : status === 'success' ? 'text-[#426b2d]' : 'text-[#547c3e]'}`}>{status === 'uploading' ? 'Processing…' : status === 'success' ? 'Uploaded successfully' : error}</p></div>}<input ref={inputRef} onChange={handleFile} accept="application/pdf" type="file" className="hidden" /></section>
}
export default UploadCard
