# Generated by Django 6.1.1 on 2026-09-19 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.documentpage')),
            ],
            options={
                'ordering': ['page__page_number', 'chunk_index'],
                'constraints': [models.UniqueConstraint(fields=('page', 'chunk_index'), name='unique_page_chunk')],
            },
        ),
    ]
